/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.iqtest;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f040003;
        public static final int green=0x7f040002;
        public static final int red=0x7f040001;
        public static final int white=0x7f040000;
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int black=0x7f020001;
        public static final int black2=0x7f020002;
        public static final int ic_launcher=0x7f020003;
        public static final int icon1=0x7f020004;
        public static final int mich=0x7f020005;
    }
    public static final class id {
        public static final int button1=0x7f080003;
        public static final int button2=0x7f080011;
        public static final int final1=0x7f080012;
        public static final int final2=0x7f080013;
        public static final int final3=0x7f080014;
        public static final int final4=0x7f080016;
        public static final int final5=0x7f080017;
        public static final int final6=0x7f080018;
        public static final int menu_settings=0x7f08001a;
        public static final int radioGroup1=0x7f080004;
        public static final int rbnt4=0x7f08000a;
        public static final int rbtn1=0x7f080007;
        public static final int rbtn2=0x7f080005;
        public static final int rbtn3=0x7f080006;
        public static final int rbtn4=0x7f080008;
        public static final int restartd=0x7f080015;
        public static final int restarte=0x7f080019;
        public static final int textView1=0x7f080009;
        public static final int textView2=0x7f08000c;
        public static final int textView3=0x7f08000b;
        public static final int textView4=0x7f08000d;
        public static final int textView5=0x7f08000e;
        public static final int tv1=0x7f08000f;
        public static final int tv2=0x7f080010;
        public static final int tv4=0x7f080000;
        public static final int tv5=0x7f080001;
        public static final int tv6=0x7f080002;
    }
    public static final class layout {
        public static final int activity_difficult1=0x7f030000;
        public static final int activity_difficult2=0x7f030001;
        public static final int activity_difficult3=0x7f030002;
        public static final int activity_difficult4=0x7f030003;
        public static final int activity_difficult5=0x7f030004;
        public static final int activity_easy1=0x7f030005;
        public static final int activity_easy2=0x7f030006;
        public static final int activity_easy3=0x7f030007;
        public static final int activity_easy4=0x7f030008;
        public static final int activity_easy5=0x7f030009;
        public static final int activity_first=0x7f03000a;
        public static final int activity_resultd=0x7f03000b;
        public static final int activity_resulte=0x7f03000c;
    }
    public static final class menu {
        public static final int activity_difficult1=0x7f070000;
        public static final int activity_difficult2=0x7f070001;
        public static final int activity_difficult3=0x7f070002;
        public static final int activity_difficult4=0x7f070003;
        public static final int activity_difficult5=0x7f070004;
        public static final int activity_easy1=0x7f070005;
        public static final int activity_easy2=0x7f070006;
        public static final int activity_easy3=0x7f070007;
        public static final int activity_easy4=0x7f070008;
        public static final int activity_easy5=0x7f070009;
        public static final int activity_first=0x7f07000a;
        public static final int activity_resultd=0x7f07000b;
        public static final int activity_resulte=0x7f07000c;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int diff1=0x7f050027;
        public static final int diff11=0x7f050028;
        public static final int diff2=0x7f050029;
        public static final int diff21=0x7f05002a;
        public static final int diff3=0x7f05002b;
        public static final int diff4=0x7f05002c;
        public static final int diff5=0x7f05002d;
        public static final int diff51=0x7f05002e;
        public static final int difficult=0x7f050011;
        public static final int easy=0x7f050010;
        public static final int easy1=0x7f050013;
        public static final int easy11=0x7f050014;
        public static final int easy2=0x7f05001e;
        public static final int easy21=0x7f05001f;
        public static final int easy31=0x7f050020;
        public static final int easy41=0x7f050022;
        public static final int easy411=0x7f050023;
        public static final int easy412=0x7f050024;
        public static final int easy413=0x7f050025;
        public static final int easy414=0x7f050026;
        public static final int easy51=0x7f050021;
        public static final int hello_world=0x7f050001;
        public static final int menu_settings=0x7f050002;
        public static final int q1difficult=0x7f050019;
        public static final int q1easy=0x7f050012;
        public static final int q2difficult=0x7f05001a;
        public static final int q2easy=0x7f050015;
        public static final int q3difficult=0x7f05001b;
        public static final int q3easy=0x7f050016;
        public static final int q4difficult=0x7f05001c;
        public static final int q4easy=0x7f050017;
        public static final int q5difficult=0x7f05001d;
        public static final int q5easy=0x7f050018;
        public static final int title_activity_difficult1=0x7f050008;
        public static final int title_activity_difficult2=0x7f050009;
        public static final int title_activity_difficult3=0x7f05000a;
        public static final int title_activity_difficult4=0x7f05000b;
        public static final int title_activity_difficult5=0x7f05000c;
        public static final int title_activity_easy1=0x7f050003;
        public static final int title_activity_easy2=0x7f050004;
        public static final int title_activity_easy3=0x7f050005;
        public static final int title_activity_easy4=0x7f050006;
        public static final int title_activity_easy5=0x7f050007;
        public static final int title_activity_resultd=0x7f050030;
        public static final int title_activity_resulte=0x7f05002f;
        public static final int welcome=0x7f05000e;
        public static final int welcome2=0x7f05000d;
        public static final int welcome3=0x7f05000f;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
    }
}
